apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: load-ingress-service
  annotations:
    # REMOVE CLASSNAME ANNOTATION
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # ADD ANNOTATION
spec:
  ingressClassName: nginx
  # ADD INGRESSCLASSNAME FIELD
  rules:
    - http:
        paths: {% for path in SrvPath %}
          - path: /{{ path.name }}/?(.*) # /?(.*) is a regex please remove it if u don't want to use it 
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ path.service_name }}
                port:
                  number: {{ path.port }}
          {% endfor %}
          - path: /api/v1/flight-routes-service/?(.*)
            # UPDATE PATH
            pathType: ImplementationSpecific
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: flight-routes-cluster-ip-service
                port:
                  number: 8000
          
          