apiVersion: v1
kind: Service
metadata:
  name: {{ Service }}
spec:
  type: {{ KubeServiceType }}
  selector:
    app: {{ Depl }}
  ports:
    - name: {{ ServiceName }}
      port: {{ Port }}
      targetPort: {{ TargetPort }}
      protocol: TCP